BIN_FOLDER = ./bin
SRC_FOLDER = ./src

NVCC=nvcc
NVCC_FLAGS=
SOURCES_FILES= $(SRC_FOLDER)/MatrixMultiply.cu $(SRC_FOLDER)/FileLibs.cpp
EXECUTABLE_FILE=$(BIN_FOLDER)/MatrixMultiply.out

all:

	$(NVCC)  $(NVCC_FLAGS) $(SOURCES_FILES) -o $(EXECUTABLE_FILE)
